// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedBy   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Card struct {
	ID          int32
	Title       string
	Description pgtype.Text
	ListID      int32
	Position    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type List struct {
	ID        int32
	Name      string
	BoardID   int32
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
}
